services:
  csvserver:
    image: infracloudio/csvserver:latest
    ports:
      - "9393:9300"
    volumes: 
      - ./inputFile:/csvserver/inputdata
    env_file:
      - csvserver.env
    # environment:
    #   - CSVSERVER_BORDER=${CSVSERVER_BORDER}
  prometheus:
    image: prom/prometheus:v2.45.2
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml